(() => {
'use strict';
let reportUI=null;
const $=id=>document.getElementById(id);if(!$('trafficRun'))return;
const modes={normal:'Normal traffic',single:'One-source DoS model',distributed:'Five-source DDoS model'};
const defenses={none:'No defense','per-source':'Per-source limit','block-source':'Block dominant overload source',layered:'Layered reservation model'};
const controls=['trafficMode','attackRate','defenseMode','serverCapacity','trafficRun'];
let timer=null,generation=0,running=false,paused=false,queue=[],tick=0,config=null,stats=null,baseline=null,last=null,actions=[],startedAt='',completedAt='',status='not-performed';
const scenes=[
 {title:'Normal traffic: everyone gets served',mode:'normal',defense:'none',story:'Three genuine visitors send six requests in each step. The server can finish ten. There is enough room for everyone.',takeaway:'Normal traffic: the server keeps up, so genuine visitors do not have to wait.'},
 {title:'DoS: one source crowds the waiting room',mode:'single',defense:'none',story:'One overload source adds 20 unwanted requests each step. The same six genuine requests still arrive. The worker cannot finish all 26 at once.',takeaway:'DoS means denial of service. Here, one source uses up room and working time. Genuine visitors may wait or be turned away.'},
 {title:'DDoS: several sources work together',mode:'distributed',defense:'none',story:'Now five sources each add four unwanted requests. That is still 20 in total. Watch the five source icons: the load is spread out, but this unprotected server faces the same total demand.',takeaway:'DDoS means distributed denial of service. The difference here is five sources instead of one. The total load is deliberately equal, so unprotected results are equal. Blocking just one source would leave four.'},
 {title:'Protection: make room for genuine visitors',mode:'distributed',defense:'layered',story:'Replay the same five-source situation. The protection gate admits at most four unwanted requests in total per step and gives genuine visitors priority. Six genuine + four unwanted requests fit the server’s ten spaces.',takeaway:'Layered protection keeps genuine visitors moving in this model. It assumes the gate can correctly recognise them. Real protection can make mistakes and needs careful testing.'}
];
let learningView='beginner',guideIndex=0,guideReady=true,lastFrame=null,paintedFrame='',runOrigin='Advanced workbench',playbackDelay=450;
const reducedMotion=()=>typeof window.matchMedia==='function'&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;
function dots(id,kinds){const host=$(id);host.replaceChildren();for(const kind of kinds){const dot=document.createElement('span');dot.className='request-dot '+kind;host.appendChild(dot);}}
function kinds(legit,attack){return Array(legit).fill('legit').concat(Array(attack).fill('attack'));}
function renderGuide(){if(!$('guidePlay'))return;const scene=scenes[guideIndex],f=guideReady?null:lastFrame,s=guideReady?zero():(stats||zero());
 $('guideSceneNumber').textContent='SCENE '+(guideIndex+1)+' OF '+scenes.length;$('guideHeading').textContent=scene.title;$('guideStory').textContent=scene.story;$('guideTakeaway').textContent=scene.takeaway;
 const sourceCount=scene.mode==='normal'?0:scene.mode==='single'?1:5;
 $('guideSources').textContent='3 genuine visitors · '+(sourceCount?sourceCount+' unwanted-traffic source'+(sourceCount===1?'':'s'):'no overload source');
 $('guideGate').textContent=scene.defense==='layered'?'Limit unwanted traffic + give genuine visitors priority':'Open gate: no protection';
 $('guideAnimation').dataset.playback=running&&!guideReady?(paused?'paused':'running'):'stopped';
 $('guidePlay').disabled=running&&!guideReady&&!(paused&&reducedMotion());$('guidePlay').textContent=reducedMotion()?'Play one step':!guideReady&&tick===12?'Replay scene':'Play animation';
 $('guidePause').disabled=!running||guideReady||(reducedMotion()&&paused);$('guidePause').textContent=paused?'Resume':'Pause';$('guideStep').disabled=(!guideReady&&running&&!paused)||(!guideReady&&tick===12);$('guideNext').disabled=guideIndex===scenes.length-1;$('guideNext').textContent=guideIndex===2?'Try protection →':'Next scene →';
 $('guideTotalServed').textContent=s.legitServed+' / '+s.legitArrived;$('guideTotalDropped').textContent=String(s.legitDropped);$('guideTotalBlocked').textContent=String(s.blocked);
 $('guideLegitArrivals').textContent=(f?f.arrivedLegit:0)+' requests this step';$('guideAttackArrivals').textContent=(f?f.arrivedAttack:0)+' requests this step';$('guideBlocked').textContent=(f?f.blocked:0)+' unwanted requests stopped this step';
 $('guideQueueCount').textContent='Waiting room: '+(f?f.queue.length:0)+' / 20';const waitingLegit=f?f.queue.filter(v=>v==='legit').length:0,waitingAttack=f?f.queue.length-waitingLegit:0;
 $('guideQueueExplanation').textContent=f&&f.queue.length?waitingLegit+' genuine + '+waitingAttack+' unwanted requests waiting.':'Empty: nobody is waiting.';
 $('guideServer').textContent='Can finish 10 requests per step';$('guideServed').textContent=(f?f.servedLegit:0)+' genuine · '+(f?f.servedAttack:0)+' unwanted';$('guideDropped').textContent=(f?f.droppedLegit:0)+' genuine · '+(f?f.droppedAttack:0)+' unwanted';
 const key=guideIndex+':'+(guideReady?'ready':tick+':'+generation);if(key!==paintedFrame){paintedFrame=key;dots('guideLegitDots',kinds(f?f.arrivedLegit:0,0));dots('guideAttackDots',kinds(0,f?f.arrivedAttack:0));dots('guideQueueDots',f?f.queue:[]);dots('guideServedDots',kinds(f?f.servedLegit:0,f?f.servedAttack:0));const host=$('guideDevices');host.replaceChildren();for(let i=0;i<3+sourceCount;i++){const el=document.createElement('span');el.className='guide-device'+(i<3?' legit':'');el.textContent=i<3?'V'+(i+1):'S'+(i-2);host.appendChild(el);}}
 if(guideReady){$('guideStepLabel').textContent='Ready · no requests have arrived in this scene';$('guideCaption').textContent='Press Play or Next step. V means genuine visitor; S means unwanted-traffic source.'+(config?' Your report keeps the previous run, including any partial results, until this scene starts.':'');}
 else if(f){$('guideStepLabel').textContent=(tick===12?'Scene complete':paused?'Paused':'Playing')+' · step '+tick+' of 12';$('guideCaption').textContent=tick===12?`This scene finished ${s.legitServed} of ${s.legitArrived} genuine requests. ${s.legitDropped} were turned away and ${waitingLegit} are still waiting. ${s.blocked} unwanted requests were stopped by the gate. ${guideIndex<3?'Choose Next scene to continue.':'Final scene complete. Your report contains only the scenes and steps you actually ran.'}`:`${f.arrivedLegit} genuine and ${f.arrivedAttack} unwanted requests arrived. The gate stopped ${f.blocked} unwanted requests. The server finished ${f.servedLegit} genuine and ${f.servedAttack} unwanted requests. ${f.queue.length} remain waiting; ${f.droppedLegit} genuine and ${f.droppedAttack} unwanted requests were turned away because the waiting room was full.`;if(status==='cancelled'){$('guideStepLabel').textContent='Stopped early · step '+tick+' of 12';$('guideCaption').textContent+=' This is a partial run.';}}
 else{$('guideStepLabel').textContent='Ready · starting scene';$('guideCaption').textContent='No step has completed yet.';}
}
function prepareGuide(index){if(running)stop(true);guideIndex=Math.max(0,Math.min(scenes.length-1,index));guideReady=true;lastFrame=null;paintedFrame='';const scene=scenes[guideIndex];$('trafficMode').value=scene.mode;$('attackRate').value='20';$('defenseMode').value=scene.defense;$('serverCapacity').value='10';if(config)$('trafficStatus').textContent='A new beginner scene is prepared. The table and report still describe the previous run until this scene starts.';renderGuide();}
function guideStart(manual){if(running)return;guideReady=false;lastFrame=null;paintedFrame='';const scene=scenes[guideIndex];$('trafficMode').value=scene.mode;$('attackRate').value='20';$('defenseMode').value=scene.defense;$('serverCapacity').value='10';run(manual||reducedMotion());}
function guideNextStep(){if(guideReady||!running){if(!guideReady&&tick===12)return;guideStart(true);}else stepOnce();}
function chooseView(view){if(view===learningView)return;if(running)stop(true);learningView=view;$('beginnerPanel').hidden=view!=='beginner';$('advancedPanel').hidden=view!=='advanced';$('beginnerView').setAttribute('aria-pressed',String(view==='beginner'));$('advancedView').setAttribute('aria-pressed',String(view==='advanced'));if(view==='beginner')prepareGuide(guideIndex);}
const now=()=>new Date().toISOString();
function log(label,result){actions.push({label,result,at:now()});if(actions.length>80)actions.shift();}
function zero(){return{legitArrived:0,legitServed:0,legitDropped:0,attackArrived:0,attackServed:0,attackDropped:0,blocked:0,peak:0,waitTicks:0};}
function lock(on){controls.forEach(id=>$(id).disabled=on);$('trafficCancel').disabled=!on;$('trafficPause').disabled=!on;$('trafficPause').textContent=paused?'Resume':'Pause';$('trafficStep').disabled=on&&!paused;renderGuide();}
function update(){const s=stats||zero();$('legitServed').textContent=s.legitServed+' / '+s.legitArrived;$('legitDropped').textContent=String(s.legitDropped);$('attackBlocked').textContent=String(s.blocked);$('queuePeak').textContent=String(s.peak);$('trafficQueue').textContent='Queue: '+queue.length+' / 20';$('trafficProgress').value=tick;renderGuide();}
function configKey(c){return c.mode+':'+c.rate;}
function percentage(s){return s.legitArrived?Math.round(s.legitServed/s.legitArrived*100):0;}
function compare(){if(!last)return;if(last.config.defense==='none'&&last.config.capacity===10){$('trafficCompare').textContent=`Undefended baseline saved for ${modes[last.config.mode]}, ${last.config.rate} attack-model requests per tick. Change the defense or capacity without changing this workload and run again.`;return;}
 if(!baseline||configKey(last.config)!==configKey(baseline.config)){$('trafficCompare').textContent='No completed, same-workload undefended baseline is available. Run this pattern and rate without defense at capacity 10, then retest with a defense or capacity change.';return;}
 const a=baseline.stats,b=last.stats;$('trafficCompare').textContent=`Same-workload evidence (capacity ${baseline.config.capacity} → ${last.config.capacity}): legitimate requests completed within 12 ticks changed from ${a.legitServed}/${a.legitArrived} (${percentage(a)}%) to ${b.legitServed}/${b.legitArrived} (${percentage(b)}%). Legitimate drops: ${a.legitDropped} → ${b.legitDropped}. Peak queue: ${a.peak} → ${b.peak}. ${last.config.mode==='distributed'&&last.config.defense==='per-source'?'Distributed sources can remain under individual limits while their combined load still competes for capacity.':'These are modeled results under the stated assumptions, not measured production performance.'}`;
}
function stop(cancelled){generation++;if(timer!==null)clearTimeout(timer);timer=null;running=false;paused=false;lock(false);if(cancelled){status='cancelled';completedAt='';$('trafficStatus').textContent=`Run cancelled at tick ${tick}/12. These are partial results; no baseline or completed comparison was saved.`;log('Cancel virtual workload',`${tick}/12 ticks completed; partial evidence only.`);}renderGuide(); }
function step(token){if(token!==generation||!running)return;timer=null;tick++;
 const attackCount=config.mode==='normal'?0:config.rate,sourceCount=config.mode==='distributed'?5:1;stats.legitArrived+=6;stats.attackArrived+=attackCount;
 let admitted=attackCount;if(config.defense==='per-source'||config.defense==='layered')admitted=Math.min(attackCount,sourceCount*4);if(config.defense==='block-source')admitted=attackCount-Math.ceil(attackCount/sourceCount);if(config.defense==='layered')admitted=Math.min(admitted,4);
 const blocked=attackCount-admitted;stats.blocked+=blocked;
 const arriving=[];for(let i=0;i<Math.max(6,admitted);i++){if(i<6)arriving.push({kind:'legit',tick});if(i<admitted)arriving.push({kind:'attack',tick});}
 // Admission before service: waiting plus new arrivals cannot exceed 20 requests.
 let dropped=0,droppedAttack=0;for(const item of arriving){if(queue.length<20)queue.push(item);else if(item.kind==='legit'){stats.legitDropped++;dropped++;}else{stats.attackDropped++;droppedAttack++;}}
 stats.peak=Math.max(stats.peak,queue.length);
 // Under the stated trusted-client assumption, layered admission reserves service.
 if(config.defense==='layered')queue.sort((a,b)=>(a.kind==='legit'?0:1)-(b.kind==='legit'?0:1));
 const served=queue.splice(0,config.capacity);let legitimateThisTick=0;for(const item of served){stats.waitTicks+=tick-item.tick;if(item.kind==='legit'){stats.legitServed++;legitimateThisTick++;}else stats.attackServed++;}
 lastFrame={arrivedLegit:6,arrivedAttack:attackCount,blocked,servedLegit:legitimateThisTick,servedAttack:served.length-legitimateThisTick,droppedLegit:dropped,droppedAttack,queue:queue.map(item=>item.kind)};
 const row=document.createElement('tr');[tick,6+attackCount,blocked,legitimateThisTick,dropped,queue.length].forEach(value=>{const cell=document.createElement('td');cell.textContent=String(value);row.appendChild(cell);});$('trafficRows').appendChild(row);update();
 $('trafficStatus').textContent=`${paused?'Paused · ':''}Tick ${tick}/12 · ${modes[config.mode]} · ${defenses[config.defense]} · ${queue.length} pending virtual requests. No network traffic is sent.`;
 if(tick===12){const pendingLegit=queue.filter(v=>v.kind==='legit').length;last={config:{...config},stats:{...stats},pendingLegit,pendingAll:queue.length};if(config.defense==='none'&&config.capacity===10)baseline=last;status='completed';completedAt=now();log('Complete virtual workload',`${modes[config.mode]}; ${defenses[config.defense]}; capacity ${config.capacity}/tick; ${stats.legitServed}/${stats.legitArrived} legitimate completed, ${stats.legitDropped} dropped, ${pendingLegit} pending; ${stats.blocked} attack-model requests blocked.`);stop(false);$('trafficStatus').textContent=`Complete: ${stats.legitServed}/${stats.legitArrived} legitimate requests completed, ${stats.legitDropped} dropped, ${pendingLegit} still queued at the observation boundary. ${stats.blocked} attack-model requests blocked. No real service was contacted.`;compare();}else if(!paused)timer=setTimeout(()=>step(token),playbackDelay);
}
function run(startPaused=false){if(running)return;const mode=$('trafficMode').value,rate=Number($('attackRate').value),defense=$('defenseMode').value,capacity=Number($('serverCapacity').value);if(![10,20].includes(capacity)||!Object.prototype.hasOwnProperty.call(modes,mode)||![10,20,30,40].includes(rate)||!Object.prototype.hasOwnProperty.call(defenses,defense)){$('trafficStatus').textContent='Choose one of the preset workload and defense options. No run started.';return;}
 runOrigin=learningView==='beginner'&&!guideReady?'Beginner scene '+(guideIndex+1)+': '+scenes[guideIndex].title:'Advanced workbench';playbackDelay=runOrigin.startsWith('Beginner')?1200:450;lastFrame=null;
 config={mode,rate:mode==='normal'?0:rate,defense,capacity};queue=[];tick=0;stats=zero();last=null;completedAt='';if(!startedAt)startedAt=now();status='in-progress';running=true;paused=startPaused;lock(true);$('trafficRows').replaceChildren();$('trafficCompare').textContent='Run in progress. Comparison is available after all 12 ticks complete.';$('trafficSources').textContent=mode==='normal'?'3 legitimate clients':`3 legitimate clients + ${mode==='single'?'1 overload source':'5 overload sources'}`;$('trafficGate').textContent=defenses[defense];$('trafficCapacity').textContent='Server: '+capacity+' / tick';log('Start virtual workload',`${runOrigin}; ${modes[mode]}; total attack-model rate ${config.rate}/tick; ${defenses[defense]}; capacity ${capacity}/tick.`);update();const token=++generation;step(token);
}
function togglePause(){if(!running)return;generation++;if(timer!==null)clearTimeout(timer);timer=null;paused=!paused;lock(true);$('trafficStatus').textContent=`${paused?'Paused':'Resuming'} at tick ${tick}/12. ${paused?'Use Step one tick or Resume; no timer is running.':'Playback continues automatically.'}`;log(paused?'Pause playback':'Resume playback',`${tick}/12 modeled ticks observed.`);if(!paused){const token=generation;timer=setTimeout(()=>step(token),playbackDelay);}}
function stepOnce(){if(running&&!paused)return;if(!running){run(true);return;}log('Step one tick',`Advance from tick ${tick} to ${tick+1}; playback stays paused.`);step(generation);}
function reset(){guideIndex=0;guideReady=true;lastFrame=null;paintedFrame='';if(reportUI)reportUI.reset();stop(false);queue=[];tick=0;config=null;stats=zero();baseline=null;last=null;actions=[];startedAt='';completedAt='';status='not-performed';$('trafficMode').value='normal';$('attackRate').value='20';$('defenseMode').value='none';$('serverCapacity').value='10';$('trafficCapacity').textContent='Server: 10 / tick';$('trafficRows').replaceChildren();$('trafficSources').textContent='3 legitimate clients';$('trafficGate').textContent='Admission policy';$('trafficStatus').textContent='Reset complete. No workload has been run in this report session.';$('trafficCompare').textContent='Finish a no-defense run at capacity 10, then repeat the same traffic pattern and rate with a defense or more capacity to compare outcomes.';update();}
['trafficMode','attackRate','defenseMode','serverCapacity'].forEach(id=>$(id).addEventListener('change',()=>{if(!running)$('trafficStatus').textContent='Settings changed. The table still describes the last run; run the workload again to test these settings.';}));
$('trafficRun').addEventListener('click',()=>run(false));$('trafficPause').addEventListener('click',togglePause);$('trafficStep').addEventListener('click',stepOnce);$('trafficCancel').addEventListener('click',()=>{if(running)stop(true);});$('trafficReset').addEventListener('click',reset);window.addEventListener('pagehide',()=>{if(running)stop(true);});
$('beginnerView').addEventListener('click',()=>chooseView('beginner'));$('advancedView').addEventListener('click',()=>chooseView('advanced'));$('guidePlay').addEventListener('click',()=>{if(running&&paused&&reducedMotion())stepOnce();else guideStart(false);});$('guidePause').addEventListener('click',()=>{if(reducedMotion()&&paused)stepOnce();else togglePause();});$('guideStep').addEventListener('click',guideNextStep);$('guideNext').addEventListener('click',()=>{if(guideIndex<scenes.length-1)prepareGuide(guideIndex+1);});$('guideReset').addEventListener('click',reset);if(typeof window.matchMedia==='function'){const motionQuery=window.matchMedia('(prefers-reduced-motion: reduce)');if(typeof motionQuery.addEventListener==='function')motionQuery.addEventListener('change',event=>{if(event.matches&&learningView==='beginner'&&running&&!paused)togglePause();renderGuide();});}renderGuide();
if(window.LabReport)reportUI=window.LabReport.mount({labId:'dos-ddos',mountTo:'#labReportMount',title:'DoS & DDoS Resilience Lab',scope:'Twelve-tick local model with three legitimate clients, zero/one/five overload sources, 10/20-request service-capacity presets and a 20-request queue. One-source blocking assumes correct identification. No packets or external requests are generated.',getSnapshot:()=>{const s=stats||zero();return{status,startedAt,completedAt,summary:config?`${runOrigin}. ${modes[config.mode]} with ${defenses[config.defense]}; ${tick}/12 modeled ticks observed at capacity ${config.capacity}/tick${paused?' (playback paused)':''}. ${s.legitServed}/${s.legitArrived} legitimate requests completed in the observation window.`:'',actions:actions.slice(),metrics:[{label:'Legitimate requests completed',value:s.legitServed+' / '+s.legitArrived},{label:'Legitimate dropped',value:s.legitDropped},{label:'Attack-model requests blocked',value:s.blocked},{label:'Pending requests at current observation',value:queue.length},{label:'Peak queue',value:s.peak},{label:'Modeled service capacity',value:config?config.capacity:10},{label:'Playback',value:running?(paused?'Paused':'Running'):'Stopped'}],findings:tick?[{title:'Modeled service availability under the chosen workload',evidence:`${s.legitServed} legitimate completed, ${s.legitDropped} dropped and ${queue.filter(v=>v.kind==='legit').length} still pending after ${tick} ticks. ${status==='cancelled'?'Run cancelled; partial evidence only.':''}`,risk:'Excess demand can consume finite capacity; pending and dropped requests are distinct.',recommendation:'Plan capacity and layered mitigation, monitor legitimate-user impact, and validate policies only in an authorized environment.'}]:[],limitations:['Deterministic queue arithmetic, not a network load test or real attack. The beginner animation uses the same calculated requests and results; dots are a visual explanation, not packets. A tick is one calculation step, not a measured real-world second.','Layered defense assumes trusted-client classification, and source blocking assumes correct identification of one overload source. Real detection can have false positives and false negatives.','Doubling service capacity is a model preset with an infrastructure-cost trade-off, not a real scaling operation or guarantee against larger attacks.','Queued requests at the observation boundary are pending, not automatically failed. Comparisons require the same workload and a completed baseline.']};}});
})();
