(() => {
'use strict';
let reportUI=null;
const $=id=>document.getElementById(id);if(!$('trafficRun'))return;
const modes={normal:'Normal traffic',single:'One-source DoS model',distributed:'Five-source DDoS model'};
const defenses={none:'No defense','per-source':'Per-source limit','block-source':'Block dominant overload source',layered:'Layered reservation model'};
const controls=['trafficMode','attackRate','defenseMode','serverCapacity','trafficRun'];
let timer=null,generation=0,running=false,paused=false,queue=[],tick=0,config=null,stats=null,baseline=null,last=null,actions=[],startedAt='',completedAt='',status='not-performed';
const now=()=>new Date().toISOString();
function log(label,result){actions.push({label,result,at:now()});if(actions.length>80)actions.shift();}
function zero(){return{legitArrived:0,legitServed:0,legitDropped:0,attackArrived:0,attackServed:0,attackDropped:0,blocked:0,peak:0,waitTicks:0};}
function lock(on){controls.forEach(id=>$(id).disabled=on);$('trafficCancel').disabled=!on;$('trafficPause').disabled=!on;$('trafficPause').textContent=paused?'Resume':'Pause';$('trafficStep').disabled=on&&!paused;}
function update(){const s=stats||zero();$('legitServed').textContent=s.legitServed+' / '+s.legitArrived;$('legitDropped').textContent=String(s.legitDropped);$('attackBlocked').textContent=String(s.blocked);$('queuePeak').textContent=String(s.peak);$('trafficQueue').textContent='Queue: '+queue.length+' / 20';$('trafficProgress').value=tick;}
function configKey(c){return c.mode+':'+c.rate;}
function percentage(s){return s.legitArrived?Math.round(s.legitServed/s.legitArrived*100):0;}
function compare(){if(!last)return;if(last.config.defense==='none'&&last.config.capacity===10){$('trafficCompare').textContent=`Undefended baseline saved for ${modes[last.config.mode]}, ${last.config.rate} attack-model requests per tick. Change the defense or capacity without changing this workload and run again.`;return;}
 if(!baseline||configKey(last.config)!==configKey(baseline.config)){$('trafficCompare').textContent='No completed, same-workload undefended baseline is available. Run this pattern and rate without defense at capacity 10, then retest with a defense or capacity change.';return;}
 const a=baseline.stats,b=last.stats;$('trafficCompare').textContent=`Same-workload evidence (capacity ${baseline.config.capacity} → ${last.config.capacity}): legitimate requests completed within 12 ticks changed from ${a.legitServed}/${a.legitArrived} (${percentage(a)}%) to ${b.legitServed}/${b.legitArrived} (${percentage(b)}%). Legitimate drops: ${a.legitDropped} → ${b.legitDropped}. Peak queue: ${a.peak} → ${b.peak}. ${last.config.mode==='distributed'&&last.config.defense==='per-source'?'Distributed sources can remain under individual limits while their combined load still competes for capacity.':'These are modeled results under the stated assumptions, not measured production performance.'}`;
}
function stop(cancelled){generation++;if(timer!==null)clearTimeout(timer);timer=null;running=false;paused=false;lock(false);if(cancelled){status='cancelled';completedAt='';$('trafficStatus').textContent=`Run cancelled at tick ${tick}/12. These are partial results; no baseline or completed comparison was saved.`;log('Cancel virtual workload',`${tick}/12 ticks completed; partial evidence only.`);} }
function step(token){if(token!==generation||!running)return;timer=null;tick++;
 const attackCount=config.mode==='normal'?0:config.rate,sourceCount=config.mode==='distributed'?5:1;stats.legitArrived+=6;stats.attackArrived+=attackCount;
 let admitted=attackCount;if(config.defense==='per-source'||config.defense==='layered')admitted=Math.min(attackCount,sourceCount*4);if(config.defense==='block-source')admitted=attackCount-Math.ceil(attackCount/sourceCount);if(config.defense==='layered')admitted=Math.min(admitted,4);
 const blocked=attackCount-admitted;stats.blocked+=blocked;
 const arriving=[];for(let i=0;i<Math.max(6,admitted);i++){if(i<6)arriving.push({kind:'legit',tick});if(i<admitted)arriving.push({kind:'attack',tick});}
 // Admission before service: waiting plus new arrivals cannot exceed 20 requests.
 let dropped=0;for(const item of arriving){if(queue.length<20)queue.push(item);else if(item.kind==='legit'){stats.legitDropped++;dropped++;}else stats.attackDropped++;}
 stats.peak=Math.max(stats.peak,queue.length);
 // Under the stated trusted-client assumption, layered admission reserves service.
 if(config.defense==='layered')queue.sort((a,b)=>(a.kind==='legit'?0:1)-(b.kind==='legit'?0:1));
 const served=queue.splice(0,config.capacity);let legitimateThisTick=0;for(const item of served){stats.waitTicks+=tick-item.tick;if(item.kind==='legit'){stats.legitServed++;legitimateThisTick++;}else stats.attackServed++;}
 const row=document.createElement('tr');[tick,6+attackCount,blocked,legitimateThisTick,dropped,queue.length].forEach(value=>{const cell=document.createElement('td');cell.textContent=String(value);row.appendChild(cell);});$('trafficRows').appendChild(row);update();
 $('trafficStatus').textContent=`${paused?'Paused · ':''}Tick ${tick}/12 · ${modes[config.mode]} · ${defenses[config.defense]} · ${queue.length} pending virtual requests. No network traffic is sent.`;
 if(tick===12){const pendingLegit=queue.filter(v=>v.kind==='legit').length;last={config:{...config},stats:{...stats},pendingLegit,pendingAll:queue.length};if(config.defense==='none'&&config.capacity===10)baseline=last;status='completed';completedAt=now();log('Complete virtual workload',`${modes[config.mode]}; ${defenses[config.defense]}; capacity ${config.capacity}/tick; ${stats.legitServed}/${stats.legitArrived} legitimate completed, ${stats.legitDropped} dropped, ${pendingLegit} pending; ${stats.blocked} attack-model requests blocked.`);stop(false);$('trafficStatus').textContent=`Complete: ${stats.legitServed}/${stats.legitArrived} legitimate requests completed, ${stats.legitDropped} dropped, ${pendingLegit} still queued at the observation boundary. ${stats.blocked} attack-model requests blocked. No real service was contacted.`;compare();}else if(!paused)timer=setTimeout(()=>step(token),450);
}
function run(startPaused=false){if(running)return;const mode=$('trafficMode').value,rate=Number($('attackRate').value),defense=$('defenseMode').value,capacity=Number($('serverCapacity').value);if(![10,20].includes(capacity)||!Object.prototype.hasOwnProperty.call(modes,mode)||![10,20,30,40].includes(rate)||!Object.prototype.hasOwnProperty.call(defenses,defense)){$('trafficStatus').textContent='Choose one of the preset workload and defense options. No run started.';return;}
 config={mode,rate:mode==='normal'?0:rate,defense,capacity};queue=[];tick=0;stats=zero();last=null;completedAt='';if(!startedAt)startedAt=now();status='in-progress';running=true;paused=startPaused;lock(true);$('trafficRows').replaceChildren();$('trafficCompare').textContent='Run in progress. Comparison is available after all 12 ticks complete.';$('trafficSources').textContent=mode==='normal'?'3 legitimate clients':`3 legitimate clients + ${mode==='single'?'1 overload source':'5 overload sources'}`;$('trafficGate').textContent=defenses[defense];$('trafficCapacity').textContent='Server: '+capacity+' / tick';log('Start virtual workload',`${modes[mode]}; total attack-model rate ${config.rate}/tick; ${defenses[defense]}; capacity ${capacity}/tick.`);update();const token=++generation;step(token);
}
function togglePause(){if(!running)return;generation++;if(timer!==null)clearTimeout(timer);timer=null;paused=!paused;lock(true);$('trafficStatus').textContent=`${paused?'Paused':'Resuming'} at tick ${tick}/12. ${paused?'Use Step one tick or Resume; no timer is running.':'Playback continues automatically.'}`;log(paused?'Pause playback':'Resume playback',`${tick}/12 modeled ticks observed.`);if(!paused){const token=generation;timer=setTimeout(()=>step(token),450);}}
function stepOnce(){if(running&&!paused)return;if(!running){run(true);return;}log('Step one tick',`Advance from tick ${tick} to ${tick+1}; playback stays paused.`);step(generation);}
function reset(){if(reportUI)reportUI.reset();stop(false);queue=[];tick=0;config=null;stats=zero();baseline=null;last=null;actions=[];startedAt='';completedAt='';status='not-performed';$('trafficMode').value='normal';$('attackRate').value='20';$('defenseMode').value='none';$('serverCapacity').value='10';$('trafficCapacity').textContent='Server: 10 / tick';$('trafficRows').replaceChildren();$('trafficSources').textContent='3 legitimate clients';$('trafficGate').textContent='Admission policy';$('trafficStatus').textContent='Reset complete. No workload has been run in this report session.';$('trafficCompare').textContent='Finish a no-defense run at capacity 10, then repeat the same traffic pattern and rate with a defense or more capacity to compare outcomes.';update();}
['trafficMode','attackRate','defenseMode','serverCapacity'].forEach(id=>$(id).addEventListener('change',()=>{if(!running)$('trafficStatus').textContent='Settings changed. The table still describes the last run; run the workload again to test these settings.';}));
$('trafficRun').addEventListener('click',()=>run(false));$('trafficPause').addEventListener('click',togglePause);$('trafficStep').addEventListener('click',stepOnce);$('trafficCancel').addEventListener('click',()=>{if(running)stop(true);});$('trafficReset').addEventListener('click',reset);window.addEventListener('pagehide',()=>{if(running)stop(true);});
if(window.LabReport)reportUI=window.LabReport.mount({labId:'dos-ddos',mountTo:'#labReportMount',title:'DoS & DDoS Resilience Lab',scope:'Twelve-tick local model with three legitimate clients, zero/one/five overload sources, 10/20-request service-capacity presets and a 20-request queue. One-source blocking assumes correct identification. No packets or external requests are generated.',getSnapshot:()=>{const s=stats||zero();return{status,startedAt,completedAt,summary:config?`${modes[config.mode]} with ${defenses[config.defense]}; ${tick}/12 modeled ticks observed at capacity ${config.capacity}/tick${paused?' (playback paused)':''}. ${s.legitServed}/${s.legitArrived} legitimate requests completed in the observation window.`:'',actions:actions.slice(),metrics:[{label:'Legitimate requests completed',value:s.legitServed+' / '+s.legitArrived},{label:'Legitimate dropped',value:s.legitDropped},{label:'Attack-model requests blocked',value:s.blocked},{label:'Pending requests at current observation',value:queue.length},{label:'Peak queue',value:s.peak},{label:'Modeled service capacity',value:config?config.capacity:10},{label:'Playback',value:running?(paused?'Paused':'Running'):'Stopped'}],findings:tick?[{title:'Modeled service availability under the chosen workload',evidence:`${s.legitServed} legitimate completed, ${s.legitDropped} dropped and ${queue.filter(v=>v.kind==='legit').length} still pending after ${tick} ticks. ${status==='cancelled'?'Run cancelled; partial evidence only.':''}`,risk:'Excess demand can consume finite capacity; pending and dropped requests are distinct.',recommendation:'Plan capacity and layered mitigation, monitor legitimate-user impact, and validate policies only in an authorized environment.'}]:[],limitations:['Deterministic queue arithmetic, not a network load test or real attack.','Layered defense assumes trusted-client classification, and source blocking assumes correct identification of one overload source. Real detection can have false positives and false negatives.','Doubling service capacity is a model preset with an infrastructure-cost trade-off, not a real scaling operation or guarantee against larger attacks.','Queued requests at the observation boundary are pending, not automatically failed. Comparisons require the same workload and a completed baseline.']};}});
})();
