(() => {
'use strict';
let reportUI=null;
const $=id=>document.getElementById(id);if(!$('xssInput'))return;
const examples={plain:'Great workshop!',format:'<b>Great workshop!</b>',event:'<img src=x onerror=alert(1)>',script:'<script>alert(1)</script>'};
let runs=[],actions=[],startedAt='',completedAt='',paired=false;const now=()=>new Date().toISOString();
const encode=text=>text.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function classify(input){if(input===examples.event)return{kind:'supplied image-event example',effect:true,supported:true,message:'MODEL ONLY: an image error handler could invoke script in an unsafe HTML context. No image, handler, or alert was actually created.'};if(input===examples.script)return{kind:'supplied script-element example',effect:true,supported:true,message:'MODEL ONLY: script-bearing content is present. Whether it runs depends on the insertion path; a script inserted using innerHTML does not normally execute. This lab executes nothing.'};const bold=input.match(/^<b>([^<>]*)<\/b>$/i);if(bold)return{kind:'simple bold markup',effect:false,supported:true,bold:bold[1],message:'The model represents this recognized formatting with a safely created bold element. It is not a general HTML renderer.'};if(!/[<>]/.test(input))return{kind:'plain text',effect:false,supported:true,message:'This input has no modeled markup. The preview is plain text.'};return{kind:'unsupported markup',effect:false,supported:false,message:'This markup is outside the teaching model. It is displayed literally; no execution or safety verdict is inferred.'};}
function compare(last){const other=[...runs].reverse().find(r=>r!==last&&r.input===last.input&&r.mode!==last.mode&&r.supported&&last.supported);paired=!!other;if(!other){$('xssComparison').textContent='No matched comparison yet. Run the other mode with exactly the same comment.';return;}completedAt=now();const before=last.mode==='html-model'?last:other;$('xssComparison').textContent=`Same-input comparison complete. Unsafe-context model: ${before.kind}. Defended output: the full comment remains literal text, with no markup interpretation. ${before.effect?'The modeled script-bearing content no longer crosses this text-output boundary.':'Try the supplied event-handler example to explore script-bearing input.'}`;}
function run(){const input=$('xssInput').value.slice(0,300),mode=$('xssMode').value;if(!['html-model','text'].includes(mode))return;if(!input.trim()){$('xssStatus').textContent='Enter demo text or load an example. No preview was run.';return;}if(!startedAt)startedAt=now();const result=classify(input),safe=mode==='text';
 $('xssBoundary').textContent=safe?'Safe comment-text boundary: create a regular text node.\n\nEquivalent HTML-text encoding:\n'+encode(input):'Unsafe-context source, shown as inert text only:\n\n'+input+'\n\nNo HTML parser or JavaScript execution is used by this model.';
 $('xssPreview').replaceChildren();if(!safe&&result.bold!==undefined){const bold=document.createElement('strong');bold.textContent=result.bold;$('xssPreview').appendChild(bold);}else $('xssPreview').textContent=input;
 $('xssEffect').hidden=safe||!result.effect;$('xssEffect').textContent=!safe&&result.effect?result.message:'';
 $('xssStatus').textContent=safe?'Defended preview: the full input is literal comment text. Angle brackets, quotes and handler names have no executable role in this text node.':result.message;
 const entry={input,mode,kind:result.kind,effect:result.effect&&!safe,supported:safe||result.supported};runs.push(entry);if(runs.length>40)runs.shift();actions.push({label:safe?'Retest with text output':'Run unsafe-context teaching model',result:`${result.kind}; ${safe?'literal text output':result.supported?'supported inert model':'unsupported markup, no verdict'}; no script executed.`,at:now()});if(actions.length>60)actions.shift();compare(entry);
 $('xssHistory').textContent=runs.slice(-8).map((r,i)=>`${runs.length-Math.min(runs.length,8)+i+1}. ${r.mode} · ${r.kind} · ${r.effect?'script-bearing content modeled':'no execution'} · inert preview`).join('\n');
}
function reset(){if(reportUI)reportUI.reset();runs=[];actions=[];startedAt='';completedAt='';paired=false;$('xssInput').value=examples.plain;$('xssExample').value='plain';$('xssMode').value='html-model';$('xssPreview').textContent='No preview yet.';$('xssEffect').hidden=true;$('xssEffect').textContent='';$('xssBoundary').textContent='No preview has been run.';$('xssStatus').textContent='Reset complete. No preview has been run in this session.';$('xssComparison').textContent='Run both modes with identical input to compare the output boundary.';$('xssHistory').textContent='No runs yet.';}
$('xssMode').addEventListener('change',()=>{$('xssStatus').textContent='Output mode changed. Run again to produce evidence for this mode.';});
$('xssRun').addEventListener('click',run);$('xssDefend').addEventListener('click',()=>{$('xssMode').value='text';run();});$('xssReset').addEventListener('click',reset);$('xssExample').addEventListener('change',()=>{const input=examples[$('xssExample').value];if(input!==undefined){$('xssInput').value=input;$('xssStatus').textContent='Example loaded. Run the safe preview model to record new evidence.';}});$('xssInput').addEventListener('input',()=>{$('xssStatus').textContent='Comment changed. The preview still describes the last recorded run; run again to test this content.';});
if(window.LabReport)reportUI=window.LabReport.mount({labId:'xss',mountTo:'#labReportMount',title:'XSS Output Safety Lab',scope:'Inert local source/sink teaching model. Only ordinary comment text and four supplied examples are interpreted by the model; no code is executed.',getSnapshot:()=>{const last=runs[runs.length-1];return{status:!runs.length?'not-performed':paired?'completed':'in-progress',startedAt,completedAt:paired?completedAt:'',summary:last?`Last recorded output mode: ${last.mode}. ${paired?'Same-input comparison completed.':'A matched comparison is still pending.'} All previews were inert.`:'',actions:actions.slice(),metrics:last?[{label:'Recorded previews',value:runs.length},{label:'Last output mode',value:last.mode}]:[],findings:runs.filter(r=>r.effect).slice(-1).map(r=>({title:'Script-bearing content at an output boundary (modeled)',evidence:`The learner ran the ${r.kind} in the unsafe-context model. Its potential effect was described, never executed.`,risk:'Interpreting untrusted data as executable markup can cause XSS in susceptible real contexts.',recommendation:'Use safe text nodes for plain comments. For required HTML, use vetted sanitization and context-specific defenses; add CSP as defense in depth.'})),limitations:['No actual script execution, browser alert, cookie access, network request, iframe or arbitrary HTML parsing occurs.','Unknown markup is outside the model. Raw comments are not included in this report.','Text output is safe for this ordinary comment-text context, not a universal sanitizer for all HTML/JS/CSS/URL contexts.']};}});
})();
