(() => {
'use strict';
let reportUI=null;
const $=id=>document.getElementById(id);if(!$('xssInput'))return;
const examples={plain:'Great workshop!',format:'<b>Great workshop!</b>',event:'<img src=x onerror=alert(1)>',script:'<script>alert(1)</script>'};
let runs=[],actions=[],startedAt='',completedAt='',paired=false,currentRun=null,inputTouched=false,guideEvent=0;const now=()=>new Date().toISOString();
const guide=window.BeginnerGuide?window.BeginnerGuide.mount({mountTo:'#beginnerGuideMount',title:'Follow a comment to the page',intro:'The source is the comment you enter. The output boundary is where a page decides whether those characters are text or instructions. This whole lab stays inert.',steps:[{title:'Choose a comment',text:'Start with plain text, load an example, or type your own comment.'},{title:'Run one mode',text:'Inspect the explanation and preview. No student script executes.'},{title:'Retest the same text',text:'Change only output handling to compare the same comment fairly.'},{title:'Compare the evidence',text:'Read what the model recognized and how the safe text boundary treats it.'}]}):null;
function currentInput(){return $('xssInput').value.slice(0,300);}
function isCurrent(){return !!currentRun&&currentRun.input===currentInput()&&currentRun.mode===$('xssMode').value;}
function updateGuide(animate=false){
 if(!guide)return;
 const active=isCurrent()?currentRun:null,input=currentInput(),mode=$('xssMode').value,validMode=['html-model','text'].includes(mode),complete=!!active&&paired;
 let step=0,completed=[],status='Ready to practise',caption='Run the plain comment first. Then try a supplied markup example and compare the same text in both output modes.',action={id:'xssRun',label:'Find Run safe preview model'};
 if(inputTouched||active){completed=[0];step=1;caption='Your comment is ready. Run the selected output mode to inspect an inert preview.';}
 if(active&&active.supported){completed=[0,1];step=2;status='One mode tested';caption=active.mode==='html-model'?'Read what the model recognized, then use text output and retest the exact same comment.':'The text-output run is recorded. Choose the unsafe-context model and run the same comment to compare both modes.';action=active.mode==='html-model'?{id:'xssDefend',label:'Find Use text output and retest'}:{id:'xssMode',label:'Find output handling'};}
 if(complete){completed=[0,1,2,3];step=3;status='Same-input comparison ready';caption=$('xssComparison').textContent;action={id:'xssExample',label:'Find another teaching example'};}
 if(active&&!active.supported){completed=[0];step=1;status='Outside this teaching model';caption='This markup is shown literally because the model does not recognize it. No safety verdict is inferred. Choose a supplied example to compare modeled behavior.';action={id:'xssExample',label:'Find supported examples'};}
 if(!input.trim()){completed=[];step=0;status='Comment needed';caption='Enter demo text or choose an example. No preview is recorded for an empty comment.';action={id:'xssInput',label:'Find comment source'};}
 if(!validMode){step=1;status='Choose an output mode';caption='Choose one of the two output modes before running the preview.';action={id:'xssMode',label:'Find output handling'};}
 if(!active&&runs.length&&input.trim()&&validMode)status='Current settings not tested';
 guide.update({step,completed,status,caption,nodes:[{label:'Comment source',value:!input.trim()?'Empty comment':active?active.kind:'Demo comment ready',tone:input.trim()?'active':'warn'},{label:'Output boundary',value:mode==='text'?'Literal text node':validMode?'HTML behavior model':'Choose a mode',tone:mode==='text'?'good':validMode?'active':'warn'},{label:'Inert preview',value:active?(mode==='text'?'Characters remain text':!active.supported?'Unknown markup · no verdict':active.effect?'Script-bearing text modeled':'Recognized text or formatting'):'Not run for these settings',tone:active?(!active.supported||active.effect?'warn':'good'):'neutral'},{label:'Comparison',value:complete?'Same comment, both modes':'Retest still needed',tone:complete?'good':'neutral'}],action,eventKey:'xss:'+guideEvent,animate});
}
function invalidate(message,animate=false){currentRun=null;paired=false;completedAt='';$('xssPreview').textContent='No preview for the current comment and mode.';$('xssEffect').hidden=true;$('xssEffect').textContent='';$('xssBoundary').textContent='No preview has been run for the current comment and mode.';$('xssStatus').textContent=message;$('xssComparison').textContent='Current settings are not tested. Earlier previews remain in Run evidence; run again before comparing.';guideEvent++;updateGuide(animate);}
const encode=text=>text.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function classify(input){if(input===examples.event)return{kind:'supplied image-event example',effect:true,supported:true,message:'MODEL ONLY: an image error handler could invoke script in an unsafe HTML context. No image, handler, or alert was actually created.'};if(input===examples.script)return{kind:'supplied script-element example',effect:true,supported:true,message:'MODEL ONLY: script-bearing content is present. Whether it runs depends on the insertion path; a script inserted using innerHTML does not normally execute. This lab executes nothing.'};const bold=input.match(/^<b>([^<>]*)<\/b>$/i);if(bold)return{kind:'simple bold markup',effect:false,supported:true,bold:bold[1],message:'The model represents this recognized formatting with a safely created bold element. It is not a general HTML renderer.'};if(!/[<>]/.test(input))return{kind:'plain text',effect:false,supported:true,message:'This input has no modeled markup. The preview is plain text.'};return{kind:'unsupported markup',effect:false,supported:false,message:'This markup is outside the teaching model. It is displayed literally; no execution or safety verdict is inferred.'};}
function compare(last){const other=[...runs].reverse().find(r=>r!==last&&r.input===last.input&&r.mode!==last.mode&&r.supported&&last.supported);paired=!!other;if(!other){$('xssComparison').textContent='No matched comparison yet. Run the other mode with exactly the same comment.';return;}completedAt=now();const before=last.mode==='html-model'?last:other;$('xssComparison').textContent=`Same-input comparison complete. Unsafe-context model: ${before.kind}. Defended output: the full comment remains literal text, with no markup interpretation. ${before.effect?'The modeled script-bearing content no longer crosses this text-output boundary.':'Try the supplied event-handler example to explore script-bearing input.'}`;}
function run(){const input=currentInput(),mode=$('xssMode').value;if(!['html-model','text'].includes(mode)){invalidate('Choose a supported output mode. No preview was run.');return;}if(!input.trim()){invalidate('Enter demo text or load an example. No preview was run.');return;}if(!startedAt)startedAt=now();const result=classify(input),safe=mode==='text';
 $('xssBoundary').textContent=safe?'Safe comment-text boundary: create a regular text node.\n\nEquivalent HTML-text encoding:\n'+encode(input):'Unsafe-context source, shown as inert text only:\n\n'+input+'\n\nNo HTML parser or JavaScript execution is used by this model.';
 $('xssPreview').replaceChildren();if(!safe&&result.bold!==undefined){const bold=document.createElement('strong');bold.textContent=result.bold;$('xssPreview').appendChild(bold);}else $('xssPreview').textContent=input;
 $('xssEffect').hidden=safe||!result.effect;$('xssEffect').textContent=!safe&&result.effect?result.message:'';
 $('xssStatus').textContent=safe?'Defended preview: the full input is literal comment text. Angle brackets, quotes and handler names have no executable role in this text node.':result.message;
 const entry={input,mode,kind:result.kind,effect:result.effect&&!safe,supported:safe||result.supported};currentRun=entry;inputTouched=true;runs.push(entry);if(runs.length>40)runs.shift();actions.push({label:safe?'Retest with text output':'Run unsafe-context teaching model',result:`${result.kind}; ${safe?'literal text output':result.supported?'supported inert model':'unsupported markup, no verdict'}; no script executed.`,at:now()});if(actions.length>60)actions.shift();compare(entry);
 $('xssHistory').textContent=runs.slice(-8).map((r,i)=>`${runs.length-Math.min(runs.length,8)+i+1}. ${r.mode} · ${r.kind} · ${r.effect?'script-bearing content modeled':'no execution'} · inert preview`).join('\n');
 guideEvent++;updateGuide(true);
}
function reset(){if(reportUI)reportUI.reset();runs=[];actions=[];startedAt='';completedAt='';paired=false;currentRun=null;inputTouched=false;$('xssInput').value=examples.plain;$('xssExample').value='plain';$('xssMode').value='html-model';$('xssPreview').textContent='No preview yet.';$('xssEffect').hidden=true;$('xssEffect').textContent='';$('xssBoundary').textContent='No preview has been run.';$('xssStatus').textContent='Reset complete. No preview has been run in this session.';$('xssComparison').textContent='Run both modes with identical input to compare the output boundary.';$('xssHistory').textContent='No runs yet.';guideEvent++;updateGuide(false);}
$('xssMode').addEventListener('change',()=>{invalidate('Output mode changed. Run again to produce evidence for this mode.',true);});
$('xssRun').addEventListener('click',run);$('xssDefend').addEventListener('click',()=>{$('xssMode').value='text';run();});$('xssReset').addEventListener('click',reset);$('xssExample').addEventListener('change',()=>{const input=examples[$('xssExample').value];if(input!==undefined){$('xssInput').value=input;inputTouched=true;invalidate('Example loaded. Run the safe preview model to record new evidence.',true);}});$('xssInput').addEventListener('input',()=>{inputTouched=true;$('xssExample').value='custom';invalidate('Comment changed. The current comment has not been tested. Earlier previews remain in Run evidence.');});
if(window.LabReport)reportUI=window.LabReport.mount({labId:'xss',mountTo:'#labReportMount',title:'XSS Output Safety Lab',scope:'Inert local source/sink teaching model. Only ordinary comment text and supplied teaching patterns are interpreted by the model; no code is executed.',getSnapshot:()=>{const last=runs[runs.length-1],active=isCurrent(),complete=active&&paired;return{status:!runs.length?'not-performed':complete?'completed':'in-progress',startedAt,completedAt:complete?completedAt:'',summary:last?`${active?'':'Current comment or mode has not been run. '}Last recorded output mode: ${last.mode}. ${complete?'Same-input comparison completed for the current comment.':'A matched comparison for the current settings is still pending.'} All previews were inert.`:'',actions:actions.slice(),metrics:last?[{label:'Recorded previews',value:runs.length},{label:'Last recorded output mode',value:last.mode}]:[],findings:runs.filter(r=>r.effect).slice(-1).map(r=>({title:'Script-bearing content at an output boundary (modeled)',evidence:`The learner ran the ${r.kind} in the unsafe-context model. Its potential effect was described, never executed.`,risk:'Interpreting untrusted data as executable markup can cause XSS in susceptible real contexts.',recommendation:'Use safe text nodes for plain comments. For required HTML, use vetted sanitization and context-specific defenses; add CSP as defense in depth.'})),limitations:['No actual script execution, browser alert, cookie access, network request, iframe or arbitrary HTML parsing occurs.','Unknown markup is outside the model. Raw comments are not included in this report.','Text output is safe for this ordinary comment-text context, not a universal sanitizer for all HTML/JS/CSS/URL contexts.']};}});
updateGuide(false);
})();
